### ISSUE TITLE
had a problem deploying to PR staging Error

### ISSUE THREAD

**Issue by Foxhunt** [zpnk/stage-ci#35] opened 2017-07-16 10:39 UTC
Hi, when opening a PR i get this Error message

it links me to [repro-name]-[branch-name].now.sh but ends in a 404.
no now deployment was created on my account

did i mess up my stage-ci setup?

Edit:
found this in the logs of my stage-ci deployment

```
Error: /bin/sh: 1: /stage-ci/node_modules/now/build/bin/now: not found

    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:34:49)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)
```

**Comment by Foxhunt** [comment] 2017-07-17 07:41
Just checked the other issues and this seems to be a duplicate of #34.

**Comment by paulirish** [comment] 2017-07-18 17:53
This looks to be different, actually. 

```
Error: /bin/sh: 1: /stage-ci/node_modules/now/build/bin/now: not found
```
vs
```
Error: /bin/sh: 1:
```

**Comment by paulirish** [comment] 2017-07-18 18:22
Yah so the bug here seems to be that your dependency isn't found. So i guess it wasn't installed? 

Or this line is failing for whatever reason: `const nowBin = path.resolve('./node_modules/now/build/bin/now');`

**Comment by Foxhunt** [comment] 2017-07-19 13:30
I redeployed the other day in case something went wrong with my stage-ci deployment.

I can find find both Errors in my logs now.

```
Error: /bin/sh: 1: 
    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:34:49)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)

Setting GitHub status to "error"...
Done!
```
and 

```
Error: /bin/sh: 1: /stage-ci/node_modules/now/build/bin/now: not found

    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:34:49)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)

Setting GitHub status to "error"...
Done!
```

The Errors occur after checking out the branch on its last commit.
Maybe i find the time to do some local debugging.

**Comment by paulirish** [comment] 2017-07-20 01:56
Yup. it's a dupe. :) 
thx man

**Comment by hugomd** [comment] 2017-07-25 00:17
Duplicate of #34

**Comment by zpnk** [comment] 2017-11-06 16:01
Fixed in [`v1.3.0`](https://github.com/zpnk/stage-ci/releases/tag/v1.3.0).

**Closed as completed by zpnk** 2017-11-06 16:01 UTC
