### ISSUE TITLE
404 deploys

### ISSUE THREAD

**Issue by mxstbr** [zpnk/stage-ci#34] opened 2017-07-11 22:06 UTC
I just set up the new version of stage-ci and pushed to a PR, this is what I got:

![stage-ci-issue](https://user-images.githubusercontent.com/7525670/28092972-399a6668-664a-11e7-982c-c86cd0802080.PNG)

This links to `<reponame>-<branchname>.now.sh` which is great except that URL just shows a Zeit 404. :cry: 

![404-deployment-not-found](https://user-images.githubusercontent.com/7525670/28093021-74b244d2-664a-11e7-8b5b-c9b385265469.PNG)

Looking at the webhook everything is green, the stage-ci server replied with 200 OK. Any ideas what the culprit could be? /cc @paulirish 

> Sidenote: Now that we have the deployment API and have links to the deploys (:tada:) maybe there could be a way to turn off the "nice" names? For obfuscation reason I'd rather like having the default now pseudo-random URLs.

**Comment by hugomd** [comment] 2017-07-13 05:28
@mxstbr Does a deployment actually occur — does anything appear when you run `now ls` ?

If the version of `now` that stage-ci uses is pinned then nothing should have changed...

I'll try to replicate this locally ✌️

**Comment by mxstbr** [comment] 2017-07-13 15:04
I'm running on a private repo maybe that why?

**Comment by mxstbr** [comment] 2017-07-13 16:25
`now ls` doesn't show any deployments so maybe I put the wrong Zeit token in or somesuch?

**Comment by mxstbr** [comment] 2017-07-13 16:25
Trying anew

**Comment by mxstbr** [comment] 2017-07-13 18:03
Nope I have a completely new deploy of stage-ci, added the webhook and everything. It says "OK" in the webhook response but there's no deploy in `now ls` and the error message still shows

**Comment by mxstbr** [comment] 2017-07-13 18:06
This is the log from the StageCI instance:

```
                > node ./src/server.js
07/13 09:45 AM
                Server listening on 3000...
07/13 11:00 AM  > Deploying org/repo@branch-name#asdf123ahfafgh834eg to https://project-branch-name.now.sh
07/13 11:00 AM  > Setting GitHub status to "pending"...
07/13 11:00 AM  > Cloning repository...
07/13 11:00 AM  > Fetching branch-name...
07/13 11:00 AM  > Checking out branch-name@asdf123ahfafgh834eg...
07/13 11:00 AM  > Setting GitHub status to "error"...
07/13 11:00 AM  Error: /bin/sh: 1:
                    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:34:49)
                    at emitOne (events.js:101:20)
                    at Socket.emit (events.js:191:7)
                    at readableAddChunk (_stream_readable.js:178:18)
                    at Socket.Readable.push (_stream_readable.js:136:10)
                    at Pipe.onread (net.js:561:20)
07/13 11:00 AM  > Done!
```

**Comment by hugomd** [comment] 2017-07-14 11:58
@mxstbr I've managed to replicate this — I think it's an issue with `git` itself, or the wrapper around it (`simple-git`). I'll see if I can resolve it 👍 

It being a private repository shouldn't be an issue either, as it uses the GitHub token to clone.

**Comment by hugomd** [comment] 2017-07-14 12:34
It's not a git issue — it gets to performing staging and fails on deployment somewhere, although it's hard to debug based on even my local error log...

I've got terribly slow internet at the moment, which is also making it difficult to debug, might be able to go to a coffee shop tomorrow to keep cracking this (amongst other things!) 

✌️

**Comment by mxstbr** [comment] 2017-07-14 17:04
Awesome, excited to get this resolved!

**Comment by paulirish** [comment] 2017-07-18 18:37
I can't reproduce this bug locally, but I've created a branch which has some extra logging so hopefully we can track this down:

https://github.com/zpnk/stage-ci/compare/master...paulirish:logging

Once change of note in here is going from `nowProc.stdout.on('close', ...` to `nowProc.on('close', ...`. AFAICT, this fixes a potential bug. This branch also checks exit codes.

screenshot of extra logging: 
![image](https://user-images.githubusercontent.com/39191/28333723-a6894420-6bad-11e7-8c39-c00e4536c21b.png)

**Comment by paulirish** [comment] 2017-07-18 18:42
Also worth pointing out that we're behind on the version of `now`. A bump to 7.2.4 _may_ possibly resolve the bug here.

**Comment by Foxhunt** [comment] 2017-07-19 13:47
also does [this](https://github.com/zeit/now-desktop/pull/329) have anything to do with the Problem?
there is still a _yarn.lock_ file in the deployment

**Comment by nikolaevigor** [comment] 2017-07-19 14:20
I have the same issue with this PR: https://github.com/nikolaevigor/yard-frontend/pull/29

**Comment by mxstbr** [comment] 2017-07-20 01:32
I ran @paulirish' branch, these are the logs:

```
Server listening on 3000...
07/19 06:30 PM  > Setting GitHub status to "pending"...
07/19 06:30 PM  > Cloning repository...
07/19 06:30 PM  > Fetching branch-name...
07/19 06:30 PM  > Checking out branch-name@a123412341235ywhfsdg8f24gywsfh...
07/19 06:30 PM  > Executing:
      now
07/19 06:30 PM  > Setting GitHub status to "error"...
07/19 06:30 PM  Error: /bin/sh: 1: /stage-ci/node_modules/now/build/bin/now: not found

    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:36:49)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)
07/19 06:30 PM  > Done!
```

> Note: Seems like the `nowProc.stderr.on` fix did it

It looks like `now` isn't correctly installed? Let's try upgrading now maybe?

**Comment by paulirish** [comment] 2017-07-20 01:56
> It looks like `now` isn't correctly installed? Let's try upgrading now maybe?

sg. you should be able to try that out locally pretty easily.

**Comment by mxstbr** [comment] 2017-07-20 17:09
Upgrading to `now@8.0.0-beta.1` throws the exact same error, so that's not the issue 😕

**Comment by paulirish** [comment] 2017-07-20 17:48
Something that stuck out to me was [this line](https://github.com/zpnk/stage-ci/blob/0ac4d679dff45814b3d4de6f19875708e3c3997b/src/core.js#L26):

```js
const nowBin = path.resolve('./node_modules/now/build/bin/now');
```

-------------

Maybe the path isn't reliable.. perhaps it may be more successful with something like this...

```js
const nowBin = path.join(require.resolve('now'), '../../bin/now');
```

Just a stab in the dark here. :)

**Comment by mxstbr** [comment] 2017-08-27 15:49
I have a public repo where this happening: https://github.com/styled-components/styled-components-website/pull/74

**Comment by jaredpalmer** [comment] 2017-08-31 22:59
@mxstbr Same thing happened to me today

**Comment by codeofsumit** [comment] 2017-09-06 14:44
I got the same problem on a private repo. Completely new stage-ci setup
these are the logs:
```
09/06 04:50 PM (44s)
> Deploying codeofsumit/med-www@test-feature#4dc2418a3f174fca7232c7b1e20f854c11f30641 to https://med-www-test-feature.now.sh
09/06 04:50 PM (43s)
> Setting GitHub status to "pending"...
09/06 04:50 PM (43s)
> Fetching test-feature...
09/06 04:50 PM (43s)
> Checking out test-feature@4dc2418a3f174fca7232c7b1e20f854c11f30641...
09/06 04:50 PM (43s)
Error: /bin/sh: 1: 
    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:34:49)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)
09/06 04:50 PM (43s)
> Setting GitHub status to "error"...
09/06 04:50 PM (42s)
> Done!
```

**Comment by codeofsumit** [comment] 2017-09-06 14:52
these are the logs:
```
09/06 04:50 PM (44s)
> Deploying codeofsumit/med-www@test-feature#4dc2418a3f174fca7232c7b1e20f854c11f30641 to https://med-www-test-feature.now.sh
09/06 04:50 PM (43s)
> Setting GitHub status to "pending"...
09/06 04:50 PM (43s)
> Fetching test-feature...
09/06 04:50 PM (43s)
> Checking out test-feature@4dc2418a3f174fca7232c7b1e20f854c11f30641...
09/06 04:50 PM (43s)
Error: /bin/sh: 1: 
    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:34:49)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)
09/06 04:50 PM (43s)
> Setting GitHub status to "error"...
09/06 04:50 PM (42s)
> Done!
```

**Comment by SaraVieira** [comment] 2017-09-09 23:00
I get the same problem on a public repo:

The logs:

```
> Setting GitHub status to "pending"...
09/09 11:41 PM (19m)
> Cloning repository...
09/09 11:41 PM (19m)
> Fetching now...
09/09 11:41 PM (19m)
> Checking out now@7f41e68c98f90074ebab4d4f6ed6d16b0ccaa814...
09/09 11:41 PM (19m)
> Setting GitHub status to "error"...
09/09 11:41 PM (19m)
Error: /bin/sh: 1: /stage-ci/node_modules/now/build/bin/now: not found

    at Socket.nowProc.stderr.on (/stage-ci/src/core.js:34:49)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)
```

https://zeit.co/saravieira/stage-ci/binxaephvp/logs

**Comment by hugomd** [comment] 2017-11-01 06:59
@mxstbr I've (hopefully) fixed this in #37, if you'd like to try it out, you can just checkout my branch:
```Bash
git clone git@github.com:hugomd/stage-ci.git
cd stage-ci
git fetch && git checkout feature/use-now-cli-binary
now deploy --npm . -e ZEIT_API_TOKEN=YOUR_TOKEN_HERE -e GITHUB_TOKEN=YOUR_TOKEN_HERE -e GITHUB_WEBHOOK_SECRET=YOUR_SECRET
```

Not sure when/if it'll be merged in, I expect @zpnk is a bit busy!

**Closed as completed** 2017-11-06 15:49 UTC

**Comment by infiniteluke** [comment] 2017-11-08 00:16
Hi @zpnk - Thanks making this cool project OSS! I'm still seeing this issue after deploying master today.

![screen shot 2017-11-07 at 4 14 24 pm](https://user-images.githubusercontent.com/1127238/32524900-c6b763a4-c3d6-11e7-8bec-2cb1eb5dd536.png)

Maybe I'm missing something? I used the link at stage.now.sh to deploy to now, which uses master of stage-ci.

**Comment by hugomd** [comment] 2017-11-08 03:51
@infiniteluke Are you running this in Docker? If you are, I suspect the issue is that the npm `build` script isn't being run, it simply installs and then runs.

https://github.com/zpnk/stage-ci/blob/408f6a02a09b642b85ab92797c5646eabf1a6a72/package.json#L10

https://github.com/zpnk/stage-ci/blob/408f6a02a09b642b85ab92797c5646eabf1a6a72/Dockerfile#L7-L14
