### ISSUE TITLE
Cannot deploy Github branch

### ISSUE THREAD

**Issue by misterfresh** [zpnk/stage-ci#36] opened 2017-07-23 13:27 UTC
Upon clicking on Deploy, nothing happens. Checking in the console, there is a request with a 500 error status code, and the body contains the message "error
:
""Response code 404 (Not Found)"""

**Comment by hugomd** [comment] 2017-07-25 00:16
Hard to say without any other error logs, but this is likely a duplicate of #34

**Comment by zpnk** [comment] 2017-11-06 16:01
Should be fixed in [`v1.3.0`](https://github.com/zpnk/stage-ci/releases/tag/v1.3.0).

**Closed as completed by zpnk** 2017-11-06 16:01 UTC
